# Generated by Django 3.0.4 on 2021-03-23 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUserinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(help_text='自建签名', max_length=255, verbose_name='用户签名')),
                ('nickname', models.CharField(help_text='自建昵称', max_length=255, verbose_name='昵称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo')),
            ],
        ),
    ]
